name: Release Syncthing

on:
  push:
    branches:
      - synology

permissions:
  contents: write

jobs:
  create-release-tag:
    name: Create release tag
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }} # https://github.com/actions/checkout/issues/882
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version: "~1.23.0"
          check-latest: true

      - name: Determine version to release
        run: |
          echo "GO_VERSION=$(go version | sed 's#^.*go##;s# .*##')" >> $GITHUB_ENV
          next=$(go run ./script/next-version.go)
          echo "NEXT=$next" >> $GITHUB_ENV
          echo "Next version is $next"

          prev=$(git describe --exclude "*-*" --abbrev=0)
          echo "PREV=$prev" >> $GITHUB_ENV
          echo "Previous version is $prev"

      - name: Determine release notes
        run: |
          echo -e "go: $GO_VERSION\n" >> relnotes/v2.md
          go run ./script/relnotes.go --new-ver "$NEXT" --branch "$GITHUB_REF_NAME" --prev-ver "$PREV" > notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Create and push tag
        run: |
          git config --global user.name 'Syncthing Release Automation'
          git config --global user.email 'release@github.com'
          git tag -a -F notes.md --cleanup=whitespace "$NEXT"
          git push origin "$NEXT"

      - name: Trigger the build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build-syncthing.yaml
          ref: refs/tags/${{ env.NEXT }}
          token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
